export class PAGE_PATH {
  // 首页的常量地址
  static readonly MAIN_PAGE: string = "main_page"
  static readonly MAIN_PAGE_ID: string = "mainNavigation"

  static readonly SEARCH_PAGE: string = "SearchView" //搜索页面的常量地址
  static readonly SEARCH_RESULT_PAGE: string = "SearchResultView" //地址结果页面的常量地址
  static readonly LOGIN_PAGE: string = "LoginView" //登录页面的常量地址
  static readonly AI_CUSTOMER_PAGE: string = "AICustomerView" // 搜索结构页面
  static readonly SETTING_PAGE: string = "SettingView" // 设置页面
  static readonly GOODS_PAGE: string = "GoodsView" // 商品详情页面
  static readonly HOME: string = "HomeView" // 商品详情页面
  //CART_PAGE
  static readonly CART: string = "CartView"
  static readonly CHECK_PAGE: string = "CheckPageView" // 核对订单页面
  static readonly PAY_PAGE: string = "PayView" // 支付页面
  static readonly PAY_RESULT_PAGE: string = "PayResultView" // 支付页面
  //我的订单
  static readonly ORDER_PAGE: string = "OrderView"

}