export class PAGE_PATH {
  // 首页的常量地址
  static readonly MAIN_PAGE: string = "main_page"
  static readonly MAIN_PAGE_ID: string = "mainNavigation"

  //搜索页面的常量地址
  static readonly SEARCH_PAGE: string = "SearchView"

  //地址结果页面的常量地址
  static readonly SEARCH_RESULT_PAGE: string = "SearchResultView"
  //登录页面的常量地址
  static readonly LOGIN_PAGE: string = "LoginView"
  static readonly AI_CUSTOMER_PAGE: string = "AICustomerView" // 搜索结构页面
  static readonly SETTING_PAGE: string = "SettingView" // 设置页面
}