# Generated by Django 5.2.5 on 2025-08-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="订单编号"
                    ),
                ),
                ("user_name", models.CharField(max_length=50, verbose_name="用户名")),
                (
                    "product_name",
                    models.CharField(max_length=100, verbose_name="商品名称"),
                ),
                ("quantity", models.IntegerField(default=1, verbose_name="购买数量")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="订单总价"
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "待支付"),
                            (1, "已支付"),
                            (2, "已发货"),
                            (3, "已完成"),
                            (4, "已取消"),
                        ],
                        default=0,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "db_table": "order",
                "ordering": ["-created_at"],
            },
        ),
    ]
