# Generated by Django 5.2.5 on 2025-08-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="名称")),
                ("logo", models.ImageField(upload_to="", verbose_name="Logo图片")),
                ("brand", models.CharField(max_length=20, verbose_name="品牌")),
                ("sales", models.IntegerField(default=0, verbose_name="销量")),
                ("stock", models.IntegerField(default=0, verbose_name="库存")),
                ("comments", models.IntegerField(default=0, verbose_name="评价数")),
                ("desc_detail", models.TextField(default="", verbose_name="详细介绍")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="单价"
                    ),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "db_table": "goods",
            },
        ),
    ]
