# Generated by Django 5.2.5 on 2025-08-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Logo图片"
            ),
        ),
    ]
