# Generated by Django 5.2.5 on 2025-08-19 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_goods_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="店铺名称")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="shop_logos/",
                        verbose_name="店铺logo",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                ("is_open", models.BooleanField(default=True, verbose_name="是否营业")),
            ],
            options={
                "verbose_name": "店铺",
                "verbose_name_plural": "店铺",
                "db_table": "shop",
            },
        ),
        migrations.CreateModel(
            name="ShopDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opening_hours",
                    models.CharField(max_length=100, verbose_name="营业时间"),
                ),
                ("description", models.TextField(verbose_name="店铺简介")),
                ("address", models.CharField(max_length=200, verbose_name="店铺地址")),
                (
                    "shop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail",
                        to="shop.shop",
                        verbose_name="关联店铺",
                    ),
                ),
            ],
            options={
                "verbose_name": "店铺详情",
                "verbose_name_plural": "店铺详情",
                "db_table": "shop_detail",
            },
        ),
    ]
