# Generated by Django 5.2.5 on 2025-08-19 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_shop_shopdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="shop",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods",
                to="shop.shop",
                verbose_name="所属店铺",
            ),
        ),
    ]
